export const PAGE_ROUTES = {
  ANCHOR: {
    EVENTS: "/#events",
    TOP: "/#top",
  },
  CONTACT: "/contact",
  CONTACT_WITH_TYPE: (type: string) => `/contact?type=${type}`,
  CREW: "/crew",
  FAQ: "/faq",
  HOME: "/",
  LEGAL: "/legal",
  LIBRARY: "/library",
  LOGIN: "/login",
  LOGIN_WITH_CHALLENGE: (token: string) => `/login?challenge=${token}`,
  LOGIN_WITH_REASON: (reason: string) => `/login?reason-hint=${reason}`,
  ME: "/me",
  ME_CHECK_IN: "/me/check-in",
  PHOTOS: "/photos",
  PHOTOS_ALBUM: (album: string) => `/photos/${album}`,
  PRESS: "/press",
  SPEAK: "/speak",
  TIMELINE: "/timeline",
  USER: (compressedId: string) => `/user/${compressedId}`,
  WATCH: (slug: string, shortId: string) => `/watch/${slug}-${shortId}`,
  WATCH_LATER: "/me/watch-later",
} as const;
